version: '3.7'

services:
  web:
    build: ./config/nginx
    env_file: .env
    volumes:
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/:cached
      - ${PROJECT_PATH}:/var/www/html:cached
      - ${PROJECT_PATH}/var/log/nginx/:/var/log/nginx/:cached
    ports:
      - 80:80

  php:
    build: ./config/php-fpm
    env_file: .env
    volumes:
      - ${PROJECT_PATH}:/var/www/html:cached
    extra_hosts:
      - "docker-host.localhost:172.17.0.1"

#  adminer:
#    image: adminer
#    restart: on-failure
#    ports:
#      - '8081:8080'