version: '3.7'

services:
  web:
    build: ./config/nginx
    env_file: .env
    volumes:
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/:cached
      - ${PROJECT_PATH}:/var/www/html:cached
      - ${PROJECT_PATH}/var/logs/nginx/:/var/log/nginx/:cached
#    ports:
#      - 8080:80

  php:
#    image: php:7-fpm
    build: ./config/php-fpm
    env_file: .env
    volumes:
      - ${PROJECT_PATH}:/var/www/html:cached
      - ${PROJECT_PATH}/var/logs/symfony:/var/www/symfony/var/log:cached
#    ports:
#      - "9000:9001"

#  adminer:
#    image: adminer
#    restart: on-failure
#    ports:
#      - '8081:8080'