version: '3.7'

services:
  web:
    build: ./config/nginx
    environment:
      - PHP_IDE_CONFIG=serverName=symfony.localhost
    ports:
      - 8080:80
    volumes:
      - ./../php-project:/var/www/html
      - ./config/nginx/:/etc/nginx/conf.d/
      - ./var/log/nginx/:/var/log/nginx/

  php:
#    image: php:7-fpm
    build: ./config/php-fpm
    environment:
      - PHP_IDE_CONFIG=serverName=symfony.localhost
    ports:
      - "9000:9001"
    volumes:
      - ./../php-project:/var/www/html

#  adminer:
#    image: adminer
#    restart: on-failure
#    ports:
#      - '8081:8080'